// PublishModelTests.swift
// SwiftAcervoTests
//
// Coverage for `Acervo.publishModel` per WU2 Sortie 2 exit criteria:
//   * Happy path — synthetic 3-file model staging dir → mock `S3CDNClient`
//     → manifest is the LAST PUT, returned `CDNManifest` matches the one
//     generated by `ManifestGenerator`.
//   * Orphan prune — existing keys include 2 stale files not in the new
//     manifest → `deleteObjects` is called exactly once with those 2 keys.
//   * `keepOrphans: true` — `deleteObjects` is NOT called.
//   * CHECK 5 failure — public `manifest.json` returns a corrupted body →
//     `AcervoError.publishVerificationFailed(stage: "CHECK 5")` is thrown.
//   * CHECK 6 failure — public sample-file body's SHA-256 mismatches.
//   * Partial-prune failure — orphan delete batch returns errors →
//     `AcervoError.publishOrphanPruneFailed(failedKeys:publishedManifest:)`
//     is thrown with the failed key list intact.
//
// The `MockURLProtocol` responder is shared between the signed S3 traffic
// (S3CDNClient ↔ `credentials.endpoint`) and the public CDN reads
// (publishModel CHECK 5/6 ↔ `credentials.publicBaseURL`). The single
// responder discriminates by URL host.
//
// All tests are nested under `SharedStaticStateSuite.MockURLProtocolSuite`
// so they inherit the `.serialized` trait and cannot race with any other
// mock-using suite.

import CryptoKit
import Foundation
import Testing

@testable import SwiftAcervo

extension SharedStaticStateSuite.MockURLProtocolSuite {

  @Suite("Acervo.publishModel")
  struct PublishModelTests {

    // MARK: - Fixtures and helpers

    /// Endpoint host the S3CDNClient will sign requests against.
    static let s3Host = "example.r2.cloudflarestorage.invalid"
    /// Public base URL host that CHECK 5 / CHECK 6 fetch from.
    static let publicHost = "cdn.example.invalid"

    static func testCredentials() -> AcervoCDNCredentials {
      AcervoCDNCredentials(
        accessKeyId: "AKIAEXAMPLE",
        secretAccessKey: "EXAMPLEKEY",
        region: "auto",
        bucket: "test-bucket",
        endpoint: URL(string: "https://\(s3Host)")!,
        publicBaseURL: URL(string: "https://\(publicHost)")!
      )
    }

    /// Creates a fresh staging directory containing N files. Returns the
    /// directory plus a dictionary of `relativePath -> SHA-256 hex`.
    static func makeStagingDir(
      files: [(name: String, contents: String)]
    ) throws -> (URL, [String: String]) {
      let dir = FileManager.default.temporaryDirectory
        .appendingPathComponent(
          "publishmodel-test-\(UUID().uuidString)",
          isDirectory: true
        )
      try FileManager.default.createDirectory(
        at: dir, withIntermediateDirectories: true
      )
      var hashes: [String: String] = [:]
      for f in files {
        let url = dir.appendingPathComponent(f.name)
        try Data(f.contents.utf8).write(to: url, options: [.atomic])
        let digest = SHA256.hash(data: Data(f.contents.utf8))
        hashes[f.name] = digest.map { String(format: "%02x", $0) }.joined()
      }
      return (dir, hashes)
    }

    /// Builds an HTTPURLResponse / Data tuple for a given request and
    /// status code. Convenience over the verbose URLResponse construction.
    static func http(
      _ request: URLRequest,
      status: Int,
      headers: [String: String] = [:],
      body: Data = Data()
    ) -> (HTTPURLResponse, Data) {
      let response = HTTPURLResponse(
        url: request.url!,
        statusCode: status,
        httpVersion: "HTTP/1.1",
        headerFields: headers
      )!
      return (response, body)
    }

    /// Records every S3 mutation request (PUT / POST / DELETE etc.)
    /// dispatched against the test endpoint host. Final-class so the
    /// closure can mutate it under the protocol's internal lock.
    final class S3RequestLog: @unchecked Sendable {
      let lock = NSLock()
      struct Entry {
        let method: String
        let path: String
        let query: String
        let body: Data?
      }
      var entries: [Entry] = []

      func record(_ entry: Entry) {
        lock.lock()
        defer { lock.unlock() }
        entries.append(entry)
      }

      func snapshot() -> [Entry] {
        lock.lock()
        defer { lock.unlock() }
        return entries
      }

      /// All PUT key paths (relative to the bucket prefix) in the order
      /// they were dispatched. Used to assert manifest.json is LAST.
      func putKeys(bucket: String) -> [String] {
        let prefix = "/\(bucket)/"
        return
          entries
          .filter { $0.method == "PUT" && !$0.query.contains("partNumber=") }
          .map { entry in
            entry.path.hasPrefix(prefix)
              ? String(entry.path.dropFirst(prefix.count))
              : entry.path
          }
      }
    }

    /// Build a multi-purpose responder that:
    ///   * Honours S3 ListObjectsV2 against `prefix` with `existingKeys`.
    ///   * 200-OKs every PUT to the bucket and returns a deterministic ETag.
    ///   * Honours bulk-delete with `deleteOutcome` per key.
    ///   * Serves the public manifest.json + sample file from
    ///     `publishedFiles` (path → bytes) once `manifest.json` has been
    ///     written by step 7.
    ///
    /// `publicSampleOverride` lets a test inject corrupted bytes for
    /// CHECK 6 failure assertions; `publicManifestOverride` does the same
    /// for CHECK 5.
    static func makeResponder(
      bucket: String,
      slug: String,
      log: S3RequestLog,
      existingKeys: [String],
      publishedFiles: @escaping @Sendable () -> [String: Data],
      deleteOutcome:
        @escaping @Sendable ([String]) -> [(key: String, success: Bool, error: String?)],
      publicManifestOverride: (@Sendable () -> Data?)? = nil,
      publicSampleOverride: (@Sendable () -> Data?)? = nil
    ) -> MockURLProtocol.Responder {
      return { request in
        let url = request.url!
        let host = url.host ?? ""
        let method = request.httpMethod ?? "GET"
        let path = url.path
        let query = url.query ?? ""

        // ---------------- public CDN reads ----------------
        if host == Self.publicHost {
          // Manifest fetch: …/models/<slug>/manifest.json
          if path.hasSuffix("/manifest.json") {
            if let override = publicManifestOverride?() {
              return Self.http(request, status: 200, body: override)
            }
            let files = publishedFiles()
            if let manifestData = files["manifest.json"] {
              return Self.http(request, status: 200, body: manifestData)
            }
            return Self.http(request, status: 404)
          }
          // Sample-file fetch: …/models/<slug>/<filename>
          if let overrideClosure = publicSampleOverride,
            let override = overrideClosure()
          {
            return Self.http(request, status: 200, body: override)
          }
          let files = publishedFiles()
          // Strip the prefix /models/<slug>/ so we look up by relative
          // file name in the publishedFiles map.
          let prefix = "/models/\(slug)/"
          let fileKey: String =
            path.hasPrefix(prefix)
            ? String(path.dropFirst(prefix.count))
            : path
          if let bytes = files[fileKey] {
            return Self.http(request, status: 200, body: bytes)
          }
          return Self.http(request, status: 404)
        }

        // ---------------- S3 traffic ----------------
        // Capture the request body up front (we need it for bulk-delete
        // parsing). httpBodyStream is the only place URLSession provides
        // body bytes for `upload(for:fromFile:)` / `upload(for:from:)`.
        let bodyData: Data? = {
          if let direct = request.httpBody, !direct.isEmpty { return direct }
          guard let stream = request.httpBodyStream else { return nil }
          stream.open()
          defer { stream.close() }
          var collected = Data()
          let bufSize = 4096
          let buffer = UnsafeMutablePointer<UInt8>.allocate(capacity: bufSize)
          defer { buffer.deallocate() }
          while stream.hasBytesAvailable {
            let read = stream.read(buffer, maxLength: bufSize)
            if read <= 0 { break }
            collected.append(buffer, count: read)
          }
          return collected
        }()

        log.record(
          .init(
            method: method,
            path: path,
            query: query,
            body: bodyData
          )
        )

        // List: GET /<bucket>?list-type=2&prefix=…
        if method == "GET" && query.contains("list-type=2") {
          var xml =
            "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
            + "<ListBucketResult>"
            + "<IsTruncated>false</IsTruncated>"
          for key in existingKeys {
            xml +=
              "<Contents>"
              + "<Key>\(key)</Key>"
              + "<Size>1</Size>"
              + "<ETag>\"e\"</ETag>"
              + "</Contents>"
          }
          xml += "</ListBucketResult>"
          return Self.http(
            request,
            status: 200,
            headers: ["Content-Type": "application/xml"],
            body: Data(xml.utf8)
          )
        }

        // Bulk delete: POST /<bucket>?delete=
        if method == "POST" && query == "delete=" {
          var keys: [String] = []
          if let body = bodyData,
            let xml = String(data: body, encoding: .utf8)
          {
            // Parse <Key>…</Key> entries with a quick scan.
            var rest = xml[...]
            while let openRange = rest.range(of: "<Key>"),
              let closeRange = rest.range(of: "</Key>", range: openRange.upperBound..<rest.endIndex)
            {
              let key = String(rest[openRange.upperBound..<closeRange.lowerBound])
              keys.append(key)
              rest = rest[closeRange.upperBound...]
            }
          }
          let outcomes = deleteOutcome(keys)
          var xml =
            "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
            + "<DeleteResult>"
          for o in outcomes {
            if o.success {
              xml += "<Deleted><Key>\(o.key)</Key></Deleted>"
            } else {
              xml +=
                "<Error>"
                + "<Key>\(o.key)</Key>"
                + "<Code>AccessDenied</Code>"
                + "<Message>\(o.error ?? "unknown")</Message>"
                + "</Error>"
            }
          }
          xml += "</DeleteResult>"
          return Self.http(
            request,
            status: 200,
            headers: ["Content-Type": "application/xml"],
            body: Data(xml.utf8)
          )
        }

        // PUT object (single-shot — file traffic is tiny in these tests).
        if method == "PUT" && !query.contains("partNumber=") {
          return Self.http(
            request,
            status: 200,
            headers: ["ETag": "\"put-etag\""]
          )
        }

        // Default: 500 so tests fail loudly on unrecognized traffic.
        return Self.http(
          request,
          status: 500,
          body: Data("unhandled \(method) \(path)?\(query)".utf8)
        )
      }
    }

    /// Registers `responder` and constructs the `S3CDNClient` + public
    /// session that `_publishModel` will drive against the mock.
    static func makeClientAndSession() -> (S3CDNClient, URLSession) {
      let session = MockURLProtocol.session()
      let client = S3CDNClient(
        credentials: testCredentials(),
        session: session
      )
      return (client, session)
    }

    /// Build a published-files snapshot keyed by relative path. The
    /// manifest.json entry is computed from `expectedManifest` so CHECK 5
    /// passes when no override is set; the sample file (`config.json` or
    /// the first manifest entry) maps to its actual on-disk bytes.
    static func snapshotPublishedFiles(
      stagingDir: URL,
      expectedManifest: CDNManifest
    ) throws -> [String: Data] {
      var out: [String: Data] = [:]
      // Encode the manifest with the same formatter ManifestGenerator uses
      // so the bytes round-trip cleanly through CHECK 5.
      let encoder = JSONEncoder()
      encoder.outputFormatting = [.prettyPrinted, .sortedKeys]
      out["manifest.json"] = try encoder.encode(expectedManifest)

      for entry in expectedManifest.files {
        let url = stagingDir.appendingPathComponent(entry.path)
        out[entry.path] = try Data(contentsOf: url)
      }
      return out
    }

    // MARK: - Test 1: happy path

    @Test("Happy path: 3 files publish, manifest.json is the LAST PUT")
    func happyPath() async throws {
      MockURLProtocol.reset()
      defer { MockURLProtocol.reset() }

      let (dir, _) = try Self.makeStagingDir(files: [
        ("config.json", "{\"hello\":1}"),
        ("tokenizer.json", "{\"vocab\":[\"a\",\"b\"]}"),
        ("weights.bin", "binary-weights-go-here"),
      ])
      defer { try? FileManager.default.removeItem(at: dir) }

      // Generate the expected manifest deterministically so we can wire
      // CHECK 5 to a body that matches.
      let expectedManifest = try await {
        let gen = ManifestGenerator(modelId: "org/repo")
        let url = try await gen.generate(directory: dir)
        let data = try Data(contentsOf: url)
        // Remove the manifest so publishModel re-generates it; the bytes
        // will be byte-identical because ManifestGenerator is deterministic
        // up to the `updatedAt` field. (Note: updatedAt may differ between
        // the two runs, so we use the SECOND manifest as the authoritative
        // snapshot below.)
        try? FileManager.default.removeItem(at: url)
        _ = data
        return try JSONDecoder().decode(CDNManifest.self, from: data)
      }()
      _ = expectedManifest  // unused in happy-path; we'll snapshot post-publish

      let log = S3RequestLog()

      // Capture the manifest the publish step writes so CHECK 5 sees
      // matching bytes. We populate this lazily on the first PUT to
      // manifest.json by reading from disk.
      let publishedSnapshot = ManifestSnapshotBox(directory: dir)

      MockURLProtocol.responder = Self.makeResponder(
        bucket: Self.testCredentials().bucket,
        slug: "org_repo",
        log: log,
        existingKeys: [],
        publishedFiles: { publishedSnapshot.snapshot() },
        deleteOutcome: { keys in
          keys.map { (key: $0, success: true, error: nil) }
        }
      )

      let (client, session) = Self.makeClientAndSession()
      let manifest = try await Acervo._publishModel(
        modelId: "org/repo",
        directory: dir,
        credentials: Self.testCredentials(),
        client: client,
        publicSession: session,
        keepOrphans: false,
        progress: nil
      )

      #expect(manifest.modelId == "org/repo")
      #expect(manifest.slug == "org_repo")
      #expect(manifest.files.count == 3)

      let putKeys = log.putKeys(bucket: Self.testCredentials().bucket)
      // Three file PUTs + one manifest PUT = four total.
      #expect(putKeys.count == 4)
      // Every non-manifest PUT must precede the manifest.json PUT.
      let manifestKey = "models/org_repo/manifest.json"
      #expect(putKeys.last == manifestKey, "manifest.json must be the last PUT")
      let nonManifestKeys = putKeys.dropLast()
      #expect(
        !nonManifestKeys.contains(manifestKey),
        "manifest.json must appear exactly once, at the end")
    }

    // MARK: - Test 2: orphan prune

    @Test("Orphan prune: deletes exactly the stale keys, one batch")
    func orphanPrune() async throws {
      MockURLProtocol.reset()
      defer { MockURLProtocol.reset() }

      let (dir, _) = try Self.makeStagingDir(files: [
        ("config.json", "{\"k\":1}"),
        ("tokenizer.json", "{\"vocab\":[\"x\"]}"),
      ])
      defer { try? FileManager.default.removeItem(at: dir) }

      let log = S3RequestLog()
      let publishedSnapshot = ManifestSnapshotBox(directory: dir)

      // Pre-existing CDN keys: two of them are stale (not in the new
      // manifest); one matches a file that's still in the manifest;
      // the last is the existing manifest.json, which is excluded from
      // the orphan computation by the implementation regardless.
      let existing = [
        "models/org_repo/config.json",  // overlaps new manifest — NOT orphan
        "models/org_repo/old-model.bin",  // orphan
        "models/org_repo/legacy/tokenizer.model",  // orphan
        "models/org_repo/manifest.json",  // explicitly excluded
      ]

      MockURLProtocol.responder = Self.makeResponder(
        bucket: Self.testCredentials().bucket,
        slug: "org_repo",
        log: log,
        existingKeys: existing,
        publishedFiles: { publishedSnapshot.snapshot() },
        deleteOutcome: { keys in
          keys.map { (key: $0, success: true, error: nil) }
        }
      )

      let (client, session) = Self.makeClientAndSession()
      _ = try await Acervo._publishModel(
        modelId: "org/repo",
        directory: dir,
        credentials: Self.testCredentials(),
        client: client,
        publicSession: session,
        keepOrphans: false,
        progress: nil
      )

      let entries = log.snapshot()
      let deleteCalls = entries.filter {
        $0.method == "POST" && $0.query == "delete="
      }
      #expect(deleteCalls.count == 1, "one bulk-delete batch for ≤1000 orphans")

      // Parse the keys passed in the bulk-delete request body.
      var deletedKeys: Set<String> = []
      if let body = deleteCalls.first?.body,
        let xml = String(data: body, encoding: .utf8)
      {
        var rest = xml[...]
        while let openRange = rest.range(of: "<Key>"),
          let closeRange = rest.range(of: "</Key>", range: openRange.upperBound..<rest.endIndex)
        {
          deletedKeys.insert(String(rest[openRange.upperBound..<closeRange.lowerBound]))
          rest = rest[closeRange.upperBound...]
        }
      }
      let expectedOrphans: Set<String> = [
        "models/org_repo/old-model.bin",
        "models/org_repo/legacy/tokenizer.model",
      ]
      #expect(
        deletedKeys == expectedOrphans,
        "orphan-prune must delete exactly the stale keys, got \(deletedKeys)")
    }

    // MARK: - Test 3: keepOrphans skips deletion

    @Test("keepOrphans: true does not invoke deleteObjects")
    func keepOrphansSkipsDeletion() async throws {
      MockURLProtocol.reset()
      defer { MockURLProtocol.reset() }

      let (dir, _) = try Self.makeStagingDir(files: [
        ("config.json", "{\"a\":1}")
      ])
      defer { try? FileManager.default.removeItem(at: dir) }

      let log = S3RequestLog()
      let publishedSnapshot = ManifestSnapshotBox(directory: dir)

      let existing = [
        "models/org_repo/old-1.bin",
        "models/org_repo/old-2.bin",
      ]

      MockURLProtocol.responder = Self.makeResponder(
        bucket: Self.testCredentials().bucket,
        slug: "org_repo",
        log: log,
        existingKeys: existing,
        publishedFiles: { publishedSnapshot.snapshot() },
        deleteOutcome: { keys in
          keys.map { (key: $0, success: true, error: nil) }
        }
      )

      let (client, session) = Self.makeClientAndSession()
      _ = try await Acervo._publishModel(
        modelId: "org/repo",
        directory: dir,
        credentials: Self.testCredentials(),
        client: client,
        publicSession: session,
        keepOrphans: true,
        progress: nil
      )

      let entries = log.snapshot()
      let deleteCalls = entries.filter {
        $0.method == "POST" && $0.query == "delete="
      }
      #expect(
        deleteCalls.isEmpty,
        "keepOrphans: true must not call deleteObjects")
    }

    // MARK: - Test 4: CHECK 5 failure (corrupted public manifest)

    @Test("CHECK 5 failure: corrupted public manifest throws publishVerificationFailed")
    func check5Failure() async throws {
      MockURLProtocol.reset()
      defer { MockURLProtocol.reset() }

      let (dir, _) = try Self.makeStagingDir(files: [
        ("config.json", "{\"x\":1}")
      ])
      defer { try? FileManager.default.removeItem(at: dir) }

      let log = S3RequestLog()
      let publishedSnapshot = ManifestSnapshotBox(directory: dir)

      // Override the public manifest body with garbage; CHECK 5 will fail
      // when JSON decoding throws.
      let corruptedManifestBody = Data("not json".utf8)

      MockURLProtocol.responder = Self.makeResponder(
        bucket: Self.testCredentials().bucket,
        slug: "org_repo",
        log: log,
        existingKeys: [],
        publishedFiles: { publishedSnapshot.snapshot() },
        deleteOutcome: { keys in
          keys.map { (key: $0, success: true, error: nil) }
        },
        publicManifestOverride: { corruptedManifestBody }
      )

      let (client, session) = Self.makeClientAndSession()
      var thrown: Error?
      do {
        _ = try await Acervo._publishModel(
          modelId: "org/repo",
          directory: dir,
          credentials: Self.testCredentials(),
          client: client,
          publicSession: session,
          keepOrphans: false,
          progress: nil
        )
      } catch {
        thrown = error
      }

      guard case .some(let err as AcervoError) = thrown,
        case .publishVerificationFailed(let stage) = err
      else {
        Issue.record(
          "Expected publishVerificationFailed, got \(String(describing: thrown))"
        )
        return
      }
      #expect(stage == "CHECK 5")
    }

    // MARK: - Test 5: CHECK 6 failure (sample-file SHA-256 mismatch)

    @Test("CHECK 6 failure: sample-file mismatch throws publishVerificationFailed")
    func check6Failure() async throws {
      MockURLProtocol.reset()
      defer { MockURLProtocol.reset() }

      let (dir, _) = try Self.makeStagingDir(files: [
        ("config.json", "{\"good\":true}")
      ])
      defer { try? FileManager.default.removeItem(at: dir) }

      let log = S3RequestLog()
      let publishedSnapshot = ManifestSnapshotBox(directory: dir)

      // Override the sample-file body with bytes whose SHA-256 will not
      // match the manifest entry. CHECK 5 still passes (manifest body
      // intact); CHECK 6 throws.
      let corruptedSample = Data("bad-bytes-not-matching-original-sha".utf8)

      MockURLProtocol.responder = Self.makeResponder(
        bucket: Self.testCredentials().bucket,
        slug: "org_repo",
        log: log,
        existingKeys: [],
        publishedFiles: { publishedSnapshot.snapshot() },
        deleteOutcome: { keys in
          keys.map { (key: $0, success: true, error: nil) }
        },
        publicSampleOverride: { corruptedSample }
      )

      let (client, session) = Self.makeClientAndSession()
      var thrown: Error?
      do {
        _ = try await Acervo._publishModel(
          modelId: "org/repo",
          directory: dir,
          credentials: Self.testCredentials(),
          client: client,
          publicSession: session,
          keepOrphans: false,
          progress: nil
        )
      } catch {
        thrown = error
      }

      guard case .some(let err as AcervoError) = thrown,
        case .publishVerificationFailed(let stage) = err
      else {
        Issue.record(
          "Expected publishVerificationFailed, got \(String(describing: thrown))"
        )
        return
      }
      #expect(stage == "CHECK 6")
    }

    // MARK: - Test 6: partial-prune failure surfaces the failed key list

    @Test("Partial-prune failure: throws publishOrphanPruneFailed with failed keys")
    func partialPruneFailure() async throws {
      MockURLProtocol.reset()
      defer { MockURLProtocol.reset() }

      let (dir, _) = try Self.makeStagingDir(files: [
        ("config.json", "{\"k\":1}")
      ])
      defer { try? FileManager.default.removeItem(at: dir) }

      let log = S3RequestLog()
      let publishedSnapshot = ManifestSnapshotBox(directory: dir)

      let orphanKey1 = "models/org_repo/old-A.bin"
      let orphanKey2 = "models/org_repo/old-B.bin"

      MockURLProtocol.responder = Self.makeResponder(
        bucket: Self.testCredentials().bucket,
        slug: "org_repo",
        log: log,
        existingKeys: [orphanKey1, orphanKey2],
        publishedFiles: { publishedSnapshot.snapshot() },
        deleteOutcome: { keys in
          // Mark every requested key as failed.
          keys.map { (key: $0, success: false, error: "denied by policy") }
        }
      )

      let (client, session) = Self.makeClientAndSession()
      var thrown: Error?
      do {
        _ = try await Acervo._publishModel(
          modelId: "org/repo",
          directory: dir,
          credentials: Self.testCredentials(),
          client: client,
          publicSession: session,
          keepOrphans: false,
          progress: nil
        )
      } catch {
        thrown = error
      }

      guard case .some(let err as AcervoError) = thrown,
        case .publishOrphanPruneFailed(let failedKeys, let publishedManifest) = err
      else {
        Issue.record(
          "Expected publishOrphanPruneFailed, got \(String(describing: thrown))"
        )
        return
      }
      #expect(
        Set(failedKeys) == Set([orphanKey1, orphanKey2]),
        "failedKeys must contain every key the orphan-prune could not remove")
      // The published manifest is surfaced so callers can record success
      // semantics with the prune-failed warning.
      #expect(publishedManifest.modelId == "org/repo")
    }

    // MARK: - Test 7: CHECK 5/6 readback bypasses caches

    /// Regression coverage for the post-upload public-readback cache
    /// hardening (PR #35 review). Without these guards, an edge or local
    /// `URLCache` entry from a prior publish could satisfy verification
    /// with stale bytes — a deployment-correctness false negative or
    /// false positive depending on topology.
    @Test("CHECK 5/6 readbacks set cb=, Cache-Control: no-cache, and reloadIgnoringLocalCacheData")
    func publicReadbackBypassesCaches() async throws {
      MockURLProtocol.reset()
      defer { MockURLProtocol.reset() }

      let (dir, _) = try Self.makeStagingDir(files: [
        ("config.json", "{\"k\":1}")
      ])
      defer { try? FileManager.default.removeItem(at: dir) }

      let log = S3RequestLog()
      let publishedSnapshot = ManifestSnapshotBox(directory: dir)

      // Capture every public-host request the responder sees so we can
      // assert on URL, headers, and cachePolicy after the publish completes.
      let publicRequests = PublicRequestLog()

      let baseResponder = Self.makeResponder(
        bucket: Self.testCredentials().bucket,
        slug: "org_repo",
        log: log,
        existingKeys: [],
        publishedFiles: { publishedSnapshot.snapshot() },
        deleteOutcome: { keys in
          keys.map { (key: $0, success: true, error: nil) }
        }
      )

      MockURLProtocol.responder = { request in
        if request.url?.host == Self.publicHost {
          publicRequests.record(request)
        }
        return baseResponder(request)
      }

      let (client, session) = Self.makeClientAndSession()
      _ = try await Acervo._publishModel(
        modelId: "org/repo",
        directory: dir,
        credentials: Self.testCredentials(),
        client: client,
        publicSession: session,
        keepOrphans: false,
        progress: nil
      )

      let captured = publicRequests.snapshot()
      // Both CHECK 5 (manifest.json) and CHECK 6 (sample file) must run
      // with cache-bypass. config.json doubles as the sample-file pick.
      let manifestReqs = captured.filter {
        ($0.url?.path ?? "").hasSuffix("/manifest.json")
      }
      let sampleReqs = captured.filter {
        ($0.url?.path ?? "").hasSuffix("/config.json")
      }
      #expect(!manifestReqs.isEmpty, "CHECK 5 manifest fetch must occur")
      #expect(!sampleReqs.isEmpty, "CHECK 6 sample-file fetch must occur")

      for request in manifestReqs + sampleReqs {
        // 1. cache-buster query parameter present
        let query = request.url?.query ?? ""
        #expect(
          query.contains("cb="),
          "public readback must carry a cb= cache-buster, got query=\(query)")
        // 2. Cache-Control: no-cache header set
        #expect(
          request.value(forHTTPHeaderField: "Cache-Control") == "no-cache",
          "public readback must set Cache-Control: no-cache")
        // 3. .reloadIgnoringLocalCacheData on the request itself
        #expect(
          request.cachePolicy == .reloadIgnoringLocalCacheData,
          "public readback must use .reloadIgnoringLocalCacheData")
      }
    }
  }
}

// MARK: - PublicRequestLog

/// Captures every public-host request the publish step issues so the
/// cache-bypass test can assert on URL, headers, and cachePolicy.
final class PublicRequestLog: @unchecked Sendable {
  private let lock = NSLock()
  private var entries: [URLRequest] = []

  func record(_ request: URLRequest) {
    lock.lock()
    defer { lock.unlock() }
    entries.append(request)
  }

  func snapshot() -> [URLRequest] {
    lock.lock()
    defer { lock.unlock() }
    return entries
  }
}

// MARK: - ManifestSnapshotBox

/// Lazily snapshots the staging directory's contents for the test
/// responder. The publish step writes `manifest.json` partway through
/// the run; the responder needs to serve those bytes in the CHECK 5 /
/// CHECK 6 fetch that follows. We re-read the disk on every snapshot()
/// call so the responder always sees the latest committed bytes.
final class ManifestSnapshotBox: @unchecked Sendable {
  private let directory: URL

  init(directory: URL) {
    self.directory = directory
  }

  func snapshot() -> [String: Data] {
    var out: [String: Data] = [:]
    let resolvedBase = directory.resolvingSymlinksInPath()
    guard
      let enumerator = FileManager.default.enumerator(
        at: resolvedBase,
        includingPropertiesForKeys: [.isRegularFileKey]
      )
    else { return out }

    let basePath = resolvedBase.path
    for case let url as URL in enumerator {
      let values = try? url.resourceValues(forKeys: [.isRegularFileKey])
      if values?.isRegularFile != true { continue }
      let resolved = url.resolvingSymlinksInPath().path
      var relative = resolved
      if resolved.hasPrefix(basePath + "/") {
        relative = String(resolved.dropFirst(basePath.count + 1))
      }
      if let bytes = try? Data(contentsOf: url) {
        out[relative] = bytes
      }
    }
    return out
  }
}
